baseURL = 'https://danielkuiper.nl/'
languageCode = 'en-us'
title = 'whoami'
theme = "hugo-theme-m10c"

# [menu]
#   [[menu.main]]
#     identifier = "home"
#     name = "Home"
#     url = "/"
#     weight = 1
#   [[menu.main]]
#     identifier = "tags"
#     name = "Tags"
#     url = "/tags/"
#     weight = 2
#   [[menu.main]]
#     identifier = "about"
#     name = "About"
#     url = "/about/"
#     weight = 3

[params]
    author = "Daniel Kuiper"
    description = "Software Development student at TCR with experience in front-end and back-end development."
    contact = "contact@danielkuiper.nl"
    menu_item_separator = " - "
    avatar = "./img/Avatar.jpg"
        [[params.social]]
          icon = "brand-github"
          name = "My Github"
          url = "https://github.com/DanielKuiper1"

        [[params.social]]
          icon = "brand-linkedin"
          name = "My LinkedIn"
          url = "https://www.linkedin.com/in/daniel-k-06471827b/"

        [params.style]
          darkestColor = "#062036"
          darkColor = "#0B3458"
          lightColor = "#FFFFFF"
          lightestColor = "#FFFFFF"
          primaryColor = "#1B84E0"
          imgColor = "#104D82"